# Generated by Django 3.2.6 on 2021-08-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episode_id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('episode', models.CharField(max_length=1000, verbose_name='感謝の言葉')),
                ('contribute_date', models.DateField(auto_now_add=True, verbose_name='投稿日時')),
                ('be_grateful_count', models.PositiveIntegerField(default=0, verbose_name='感謝された回数')),
                ('public', models.BooleanField(default=True, verbose_name='公開有無')),
            ],
        ),
    ]
